spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liquibase
    username: root
    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#  liquibase:
#    change-log: classpath:liquibase/db-changelog.xml
liquibase:
  dir: src/main/resources/liquibase
  drop: true